const pptxgen = require('pptxgenjs');
const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE';
pptx.author = 'Nhóm HTT19';
pptx.subject = 'Design Patterns trong hệ thống quản lý khách sạn và Homestay';
pptx.title = 'HTT19 - Design Patterns';
pptx.company = 'HTT19';
pptx.lang = 'vi-VN';
pptx.theme = { headFontFace: 'Aptos Display', bodyFontFace: 'Aptos', lang: 'vi-VN' };
const navy = '102A43', teal = '0E7490', gold = 'F59E0B', ink = '172B4D', muted = '52606D', white = 'FFFFFF', pale = 'F0F9FF';
function addSlide(title, subtitle='') { const s=pptx.addSlide(); s.background={color:white}; s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:13.333,h:0.2,fill:{color:teal},line:{color:teal}}); s.addText(title,{x:0.65,y:0.55,w:12,h:0.55,fontFace:'Aptos Display',fontSize:26,bold:true,color:navy,margin:0}); if(subtitle) s.addText(subtitle,{x:0.68,y:1.18,w:11.8,h:0.3,fontSize:11,color:muted,margin:0}); s.addText('HTT19  |  Phát triển ứng dụng hướng đối tượng',{x:0.65,y:7.12,w:8,h:0.2,fontSize:8,color:muted,margin:0}); return s; }
function bullets(s, items, x=0.9,y=1.75,w=11.5,fs=20){ s.addText(items.map(t=>({text:t,options:{bullet:{indent:18},hanging:4}})),{x,y,w,h:4.8,fontSize:fs,color:ink,breakLine:false,paraSpaceAfterPt:14,margin:0.05,fit:'shrink'}); }
let s=addSlide('Áp dụng Design Pattern','Hệ thống Quản lý Khách sạn và Homestay HTT19'); s.addText('Từ lý thuyết đến triển khai Python',{x:0.9,y:2.2,w:7.8,h:0.6,fontSize:30,bold:true,color:teal,margin:0}); s.addText('Báo cáo 30 phút  •  Nhóm HTT19',{x:0.95,y:3.05,w:6,h:0.35,fontSize:17,color:muted,margin:0}); s.addShape(pptx.ShapeType.roundRect,{x:9.3,y:2.0,w:2.6,h:2.6,rectRadius:0.12,fill:{color:pale},line:{color:teal,width:2}}); s.addText('HOTEL\nSYSTEM',{x:9.65,y:2.75,w:1.9,h:1,fontSize:20,bold:true,color:navy,align:'center',valign:'mid',margin:0});
s=addSlide('1. Bối cảnh và mục tiêu'); bullets(s,['Quản lý phòng, khách hàng và dịch vụ đi kèm.','Thực hiện check-in, check-out và thanh toán.','Hỗ trợ nhiều cổng thanh toán: VNPay, MoMo, Credit Card.','Áp dụng chính sách giảm giá linh hoạt.','Thống kê doanh thu theo tháng và sẵn sàng triển khai Cloud/Hosting.']);
s=addSlide('2. Design Pattern là gì?'); bullets(s,['Giải pháp tổng quát, đã được kiểm chứng cho các vấn đề thiết kế thường gặp.','Không phải thư viện hay đoạn mã sao chép cố định.','Là cách tổ chức lớp, đối tượng và mối quan hệ giữa chúng.','Mục tiêu: giảm phụ thuộc, tăng tái sử dụng và dễ mở rộng.']);
s=addSlide('3. Ba nhóm Design Pattern'); const cols=[['Creational','Singleton\nFactory Method\nAbstract Factory',teal],['Structural','Adapter\nRepository',gold],['Behavioral','Observer\nStrategy',navy]]; cols.forEach((c,i)=>{let x=0.8+i*4.15; s.addShape(pptx.ShapeType.roundRect,{x,y:2,w:3.55,h:2.5,rectRadius:0.08,fill:{color:c[2]},line:{color:c[2]}}); s.addText(c[0],{x:x+0.25,y:2.35,w:3,h:0.4,fontSize:21,bold:true,color:white,align:'center',margin:0}); s.addText(c[1],{x:x+0.3,y:2.95,w:2.95,h:1.2,fontSize:17,color:white,align:'center',breakLine:false,margin:0.05});});
s=addSlide('4. Singleton: AppConfigManager'); bullets(s,['Đảm bảo toàn hệ thống chỉ dùng một đối tượng cấu hình.','Phù hợp với config, logger, database connection hoặc cache.','Trong HTT19: lưu tên ứng dụng, cơ sở dữ liệu và đơn vị tiền tệ.','Kiểm chứng bằng: config_1 is config_2  →  True']);
s=addSlide('5. Factory: cổng thanh toán'); bullets(s,['Client chỉ yêu cầu loại thanh toán, không phụ thuộc class cụ thể.','PaymentFactory tạo VNPay, MoMo hoặc CreditCard.','Thêm gateway mới mà không sửa nghiệp vụ check-out.','Ví dụ: PaymentFactory.create_payment("momo").']);
s=addSlide('6. Strategy: giảm giá runtime'); bullets(s,['Đóng gói từng thuật toán giảm giá thành một strategy.','VIP: 20%  •  Khách mới: 10%  •  Flash Sale: 30%.','DiscountCalculator nhận strategy qua constructor.','Có thể thay đổi chiến lược mà không sửa calculator.']);
s=addSlide('7. Repository và Adapter'); bullets(s,['Repository trừu tượng hóa truy cập dữ liệu phòng.','BookingService không cần biết dữ liệu nằm trong bộ nhớ hay SQL.','Adapter chuyển đổi dữ liệu giữa API thanh toán và mô hình nội bộ.','Kết quả: dễ thay thế công nghệ và dễ kiểm thử.']);
s=addSlide('8. IoC và DI Container'); bullets(s,['IoC: đảo ngược quyền kiểm soát việc tạo dependency.','DI: truyền dependency từ bên ngoài vào class.','DIContainer đăng ký và resolve AppConfigManager, Repository, Service.','Giảm coupling và hỗ trợ test bằng mock repository.']);
s=addSlide('9. Use Case tổng quát','Các actor và chức năng chính của hệ thống'); s.addText('Quản trị viên: phòng, khách hàng, dịch vụ, báo cáo\nLễ tân: đặt phòng, check-in, check-out, thanh toán\nKhách hàng: đặt phòng, thanh toán\nCổng thanh toán: xử lý giao dịch',{x:1.2,y:2,w:10.8,h:2.8,fontSize:24,color:ink,align:'center',valign:'mid',margin:0.1});
s=addSlide('10. Use Case chi tiết: Check-in'); bullets(s,['Tìm thông tin đặt phòng.','Xác minh thông tin khách hàng.','Kiểm tra tình trạng phòng.','Cập nhật trạng thái phòng thành occupied.','Tạo phiếu nhận phòng.']);
s=addSlide('11. Use Case chi tiết: Check-out'); bullets(s,['Tính tiền phòng và dịch vụ.','Áp dụng Strategy giảm giá.','Tạo hóa đơn và chọn cổng thanh toán.','Cập nhật trạng thái phòng.','Ghi nhận doanh thu theo tháng.']);
s=addSlide('12. Demo luồng nghiệp vụ'); bullets(s,['Khách check-out với tổng tiền ban đầu 5.000.000 VND.','Strategy VIP giảm 20% → còn 4.000.000 VND.','Factory tạo gateway MoMo.','Gateway xử lý thanh toán và hệ thống ghi nhận doanh thu.']);
s=addSlide('13. Đánh giá kiến trúc'); bullets(s,['Ưu điểm: rõ ràng, dễ mở rộng, dễ bảo trì, dễ kiểm thử.','Factory mở rộng phương thức thanh toán.','Strategy mở rộng chính sách giá.','Repository tách nghiệp vụ khỏi CSDL.','Hạn chế: tăng số lượng class và không nên lạm dụng pattern.']);
s=addSlide('14. Kết luận'); s.addText('Design Pattern biến bài toán thực tế thành kiến trúc có thể mở rộng.',{x:1,y:2,w:11.2,h:0.7,fontSize:26,bold:true,color:teal,align:'center',margin:0}); bullets(s,['Singleton quản lý cấu hình dùng chung.','Factory khởi tạo cổng thanh toán linh hoạt.','Strategy thay đổi thuật toán giảm giá runtime.','DI Container quản lý dependency và giảm coupling.'],1.4,3.1,10.4,20); s.addText('Cảm ơn thầy/cô và các bạn đã lắng nghe.',{x:1,y:6.2,w:11,h:0.4,fontSize:18,bold:true,color:navy,align:'center',margin:0});
pptx.writeFile({ fileName: 'HTT19_Design_Patterns.pptx' });
      
