'use client'

import { useMemo, useState } from 'react'
import {
  BedDouble, Bell, CalendarCheck, CalendarDays, CheckCircle2, ChevronRight,
  CircleDollarSign, ClipboardList, Coffee, FileCode2, LayoutDashboard, Menu,
  Plus, Search, Settings, Sparkles, Users, Utensils, X, Zap,
} from 'lucide-react'

type Trang = 'Tổng quan' | 'Đặt phòng' | 'Phòng' | 'Khách hàng' | 'Dịch vụ' | 'Doanh thu' | 'Thiết kế'
type TrangThaiPhong = 'Đang ở' | 'Trống' | 'Dọn phòng' | 'Bảo trì'

const danhSachPhong: { ma: string; ten: string; khach: string; gia: string; trangThai: TrangThaiPhong; mau: string }[] = [
  { ma: '101', ten: 'Standard King', khach: 'Nguyễn Minh Anh', gia: '850.000đ', trangThai: 'Đang ở', mau: 'xanh' },
  { ma: '102', ten: 'Standard Twin', khach: '—', gia: '780.000đ', trangThai: 'Trống', mau: 'la' },
  { ma: '103', ten: 'Deluxe Garden', khach: 'Trần Hoàng Nam', gia: '1.250.000đ', trangThai: 'Đang ở', mau: 'xanh' },
  { ma: '104', ten: 'Deluxe Garden', khach: '—', gia: '1.250.000đ', trangThai: 'Dọn phòng', mau: 'cam' },
  { ma: '201', ten: 'Family Suite', khach: 'Lê Thu Hà', gia: '2.100.000đ', trangThai: 'Đang ở', mau: 'xanh' },
  { ma: '202', ten: 'Family Suite', khach: '—', gia: '2.100.000đ', trangThai: 'Bảo trì', mau: 'xam' },
]

const doanhThu = [42, 58, 47, 66, 61, 74, 69, 82, 77, 91, 84, 96]
const mucYeuCau = [
  ['Singleton', 'AppConfigManager quản lý cấu hình ứng dụng', 'Creational', 'Đã cài đặt'],
  ['Factory', 'Tạo cổng thanh toán VNPay, Momo, CreditCard', 'Creational', 'Đã cài đặt'],
  ['Strategy', 'Tính giảm giá VIP, khách mới, Flash Sale', 'Behavioral', 'Đã cài đặt'],
  ['Repository', 'Trừu tượng hóa tầng cơ sở dữ liệu phòng', 'Structural', 'Đã cài đặt'],
  ['DI Container', 'Đăng ký và inject BookingService', 'IoC / DI', 'Đã cài đặt'],
  ['Use Case', 'Sơ đồ tổng quát và 2 chức năng cốt lõi', 'Thực hành', 'Có trong thư mục diagrams'],
]

export default function TrangChinh() {
  const [trangHienTai, setTrangHienTai] = useState<Trang>('Tổng quan')
  const [moMenu, setMoMenu] = useState(false)
  const [moDatPhong, setMoDatPhong] = useState(false)
  const [tuKhoa, setTuKhoa] = useState('')
  const [thongBao, setThongBao] = useState('')
  const [boLoc, setBoLoc] = useState<TrangThaiPhong | 'Tất cả'>('Tất cả')

  const phongHienThi = useMemo(() => danhSachPhong.filter((phong) => {
    const khopTuKhoa = `${phong.ma} ${phong.ten} ${phong.khach}`.toLowerCase().includes(tuKhoa.toLowerCase())
    return khopTuKhoa && (boLoc === 'Tất cả' || phong.trangThai === boLoc)
  }), [tuKhoa, boLoc])

  function hienThongBao(noiDung: string) {
    setThongBao(noiDung)
    window.setTimeout(() => setThongBao(''), 2600)
  }

  const menu = [
    [LayoutDashboard, 'Tổng quan'], [CalendarDays, 'Đặt phòng'], [BedDouble, 'Phòng'],
    [Users, 'Khách hàng'], [Utensils, 'Dịch vụ'], [CircleDollarSign, 'Doanh thu'],
  ] as const

  return (
    <main className="min-h-screen bg-[#f5f8f8] text-[#132b35]">
      <aside className={`fixed inset-y-0 left-0 z-40 w-[252px] border-r border-[#dcebea] bg-[#102f3a] px-5 py-6 text-white transition-transform lg:translate-x-0 ${moMenu ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-2xl bg-[#e8bd72] text-[#102f3a]"><BedDouble size={21} /></div><div><p className="text-[15px] font-bold">HTT19 Stay</p><p className="text-[11px] text-[#aac3c5]">Hotel & Homestay</p></div></div>
          <button className="lg:hidden" onClick={() => setMoMenu(false)} aria-label="Đóng menu"><X size={18} /></button>
        </div>
        <div className="mt-9 rounded-2xl border border-white/10 bg-white/5 p-3"><p className="text-[10px] uppercase tracking-[0.18em] text-[#a9c1c2]">Hôm nay</p><div className="mt-2 flex items-end justify-between"><strong className="text-2xl">78%</strong><span className="text-[11px] text-[#e8bd72]">+5,2%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[78%] rounded-full bg-[#e8bd72]" /></div></div>
        <p className="mb-3 mt-8 px-3 text-[10px] font-bold uppercase tracking-[0.18em] text-[#82a6a8]">Vận hành</p>
        <nav className="space-y-1">{menu.map(([BieuTuong, nhan]) => <button key={nhan} onClick={() => { setTrangHienTai(nhan); setMoMenu(false) }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[13px] font-medium transition ${trangHienTai === nhan ? 'bg-[#e8bd72] text-[#102f3a] shadow-lg shadow-black/10' : 'text-[#c4d7d8] hover:bg-white/10'}`}><BieuTuong size={17} strokeWidth={1.8} /><span>{nhan}</span>{nhan === 'Đặt phòng' && <span className="ml-auto rounded-full bg-[#d7ece8] px-2 py-0.5 text-[10px] text-[#12626b]">12</span>}</button>)}</nav>
        <p className="mb-3 mt-8 px-3 text-[10px] font-bold uppercase tracking-[0.18em] text-[#82a6a8]">Bài tập Design Pattern</p>
        <button onClick={() => setTrangHienTai('Thiết kế')} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[13px] font-medium ${trangHienTai === 'Thiết kế' ? 'bg-white/15 text-white' : 'text-[#c4d7d8] hover:bg-white/10'}`}><FileCode2 size={17} />Đối chiếu yêu cầu</button>
        <button onClick={() => hienThongBao('Đã mở phần cài đặt')} className="mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[13px] text-[#c4d7d8] hover:bg-white/10"><Settings size={17} />Cài đặt</button>
        <div className="absolute bottom-6 left-5 right-5 flex items-center gap-2 rounded-2xl bg-white/10 p-3"><div className="flex size-8 items-center justify-center rounded-full bg-[#e8bd72] text-xs font-bold text-[#102f3a]">BQ</div><div><p className="text-xs font-semibold">Bích Quyên</p><p className="text-[10px] text-[#a9c1c2]">Quản trị viên</p></div></div>
      </aside>

      <section className="lg:pl-[252px]">
        <header className="flex h-[78px] items-center justify-between border-b border-[#dcebea] bg-white/90 px-5 backdrop-blur sm:px-8"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={() => setMoMenu(true)} aria-label="Mở menu"><Menu size={21} /></button><div><p className="text-[11px] text-slate-400">Thứ Tư, 25 tháng 9, 2026</p><h1 className="mt-1 text-lg font-bold">{trangHienTai}</h1></div></div><div className="flex items-center gap-3"><button onClick={() => hienThongBao('Bạn có 3 thông báo cần xử lý')} className="relative rounded-xl p-2 text-slate-500 hover:bg-slate-100" aria-label="Thông báo"><Bell size={19} /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-[#e98b69]" /></button><div className="hidden items-center gap-2 sm:flex"><div className="flex size-8 items-center justify-center rounded-full bg-[#d7ece8] text-xs font-bold text-[#12626b]">BQ</div><span className="text-xs font-semibold">Bích Quyên</span></div></div></header>

        <div className="mx-auto max-w-[1450px] px-5 py-6 sm:px-8">
          <div className="relative mb-6 overflow-hidden rounded-[26px] bg-[#123f50] px-6 py-7 text-white shadow-xl shadow-[#123f50]/10 sm:px-8"><div className="absolute -right-8 -top-16 size-64 rounded-full border-[28px] border-[#e8bd72]/20" /><div className="absolute -bottom-24 right-44 size-48 rounded-full bg-[#5db8ac]/20 blur-2xl" /><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs text-[#b9d5d2]"><Sparkles size={14} className="text-[#e8bd72]" />Trung tâm vận hành HTT19 Stay</div><h2 className="max-w-xl text-2xl font-bold tracking-tight sm:text-3xl">Xin chào Bích Quyên, sẵn sàng cho một ngày thật hiệu quả?</h2><p className="mt-2 max-w-lg text-xs leading-5 text-[#b9d5d2]">Theo dõi toàn bộ phòng, khách lưu trú, dịch vụ và doanh thu trên một màn hình.</p></div><button onClick={() => setMoDatPhong(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[#e8bd72] px-4 py-3 text-xs font-bold text-[#123f50] transition hover:bg-[#f2ce8d]"><Plus size={16} />Tạo đặt phòng</button></div></div>

          {trangHienTai === 'Thiết kế' ? <section className="rounded-2xl border border-[#dcebea] bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#16806e]">Phần bám sát yêu cầu</p><h2 className="mt-2 text-2xl font-bold">Design Pattern trong đề tài HTT19</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Màn hình này giúp nhóm trình bày trực tiếp phần lý thuyết và thực hành đã cài đặt trong hệ thống quản lý khách sạn, thay vì chỉ chiếu code rời rạc.</p></div><div className="hidden rounded-2xl bg-[#edf8f6] p-4 text-[#16806e] sm:block"><CheckCircle2 size={28} /></div></div><div className="mt-7 grid gap-3 md:grid-cols-2">{mucYeuCau.map(([ten, moTa, nhom, ketQua]) => <div key={ten} className="rounded-2xl border border-slate-100 bg-[#fbfdfd] p-4 transition hover:-translate-y-0.5 hover:border-[#b9ddd7] hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="rounded-lg bg-[#e8f2f2] px-2 py-1 text-[10px] font-bold text-[#12626b]">{nhom}</span><h3 className="text-sm font-bold">{ten}</h3></div><p className="mt-2 text-xs leading-5 text-slate-500">{moTa}</p></div><CheckCircle2 size={18} className="shrink-0 text-[#32a47f]" /></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-[11px]"><span className="text-slate-400">Trạng thái</span><span className="font-semibold text-[#16806e]">{ketQua}</span></div></div>)}</div><div className="mt-6 rounded-2xl bg-[#102f3a] p-5 text-white"><div className="flex items-center gap-2 text-sm font-bold"><Zap size={16} className="text-[#e8bd72]" />Luồng demo thuyết trình</div><p className="mt-2 text-xs leading-6 text-[#b9d5d2]">Singleton giữ cấu hình → Factory chọn cổng thanh toán → Strategy tính giảm giá → DI Container cung cấp BookingService. Đây là luồng nghiệp vụ check-out thực tế của HTT19 Stay.</p></div></section> : <>
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[CircleDollarSign, 'Doanh thu tháng này', '186.450.000đ', '+12,8%', 'teal'], [ClipboardList, 'Đặt phòng hôm nay', '12', '+3', 'blue'], [BedDouble, 'Công suất phòng', '78,4%', '+5,2%', 'orange'], [Users, 'Khách đang lưu trú', '34', '+8', 'purple']].map(([BieuTuong, tieuDe, giaTri, thayDoi, mau]) => <div key={tieuDe as string} className="rounded-2xl border border-[#dcebea] bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between"><div className={`flex size-10 items-center justify-center rounded-xl ${mau === 'teal' ? 'bg-[#e3f2ef] text-[#16806e]' : mau === 'blue' ? 'bg-[#e8f0fb] text-[#4171ae]' : mau === 'orange' ? 'bg-[#fff0e5] text-[#dc8753]' : 'bg-[#f0eafa] text-[#8563b8]'}`}><BieuTuong size={18} /></div><span className="rounded-full bg-[#e8f5ee] px-2 py-1 text-[10px] font-semibold text-[#32916b]">{thayDoi}</span></div><p className="mt-5 text-xs text-slate-500">{tieuDe}</p><p className="mt-1 text-xl font-bold tracking-tight">{giaTri}</p><div className="mt-3 h-1.5 rounded-full bg-slate-100"><div className={`h-full rounded-full ${mau === 'orange' ? 'w-[72%] bg-[#e8a36f]' : 'w-[84%] bg-[#58a99c]'}`} /></div></div>)}</div>

            <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]"><div className="rounded-2xl border border-[#dcebea] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="text-sm font-bold">Doanh thu theo tháng</h3><p className="mt-1 text-[11px] text-slate-400">Tăng trưởng ổn định trong năm 2026</p></div><button onClick={() => setTrangHienTai('Doanh thu')} className="flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-[11px] font-medium text-slate-500">Chi tiết <ChevronRight size={13} /></button></div><div className="mt-6 flex h-[175px] items-end gap-1 sm:gap-3">{doanhThu.map((chieuCao, chiSo) => <div key={chiSo} className="group flex flex-1 flex-col items-center gap-2"><div className={`relative w-full rounded-t-md transition group-hover:bg-[#e8bd72] ${chiSo === 11 ? 'bg-[#123f50]' : 'bg-[#cce5e1]'}`} style={{ height: `${chieuCao}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 rounded bg-[#132b35] px-2 py-1 text-[9px] text-white group-hover:block">{chieuCao * 2}tr</span></div><span className="text-[9px] text-slate-400">T{chiSo + 1}</span></div>)}</div></div><div className="rounded-2xl border border-[#dcebea] bg-white p-5 shadow-sm"><h3 className="text-sm font-bold">Tình trạng phòng</h3><p className="mt-1 text-[11px] text-slate-400">48 phòng trong hệ thống</p><div className="mt-5 flex items-center gap-5"><div className="relative flex size-32 shrink-0 items-center justify-center rounded-full" style={{ background: 'conic-gradient(#123f50 0 78%, #e8a36f 78% 87%, #8ec9c0 87% 96%, #e6e8ec 96% 100%)' }}><div className="flex size-[92px] flex-col items-center justify-center rounded-full bg-white"><strong className="text-xl">78%</strong><span className="text-[10px] text-slate-400">đang sử dụng</span></div></div><div className="space-y-3 text-[11px] text-slate-500"><p><i className="mr-2 inline-block size-2 rounded-full bg-[#123f50]" />Đang ở <b className="ml-2 text-slate-700">38</b></p><p><i className="mr-2 inline-block size-2 rounded-full bg-[#e8a36f]" />Dọn phòng <b className="ml-2 text-slate-700">4</b></p><p><i className="mr-2 inline-block size-2 rounded-full bg-[#8ec9c0]" />Trống <b className="ml-2 text-slate-700">5</b></p><p><i className="mr-2 inline-block size-2 rounded-full bg-slate-200" />Bảo trì <b className="ml-2 text-slate-700">1</b></p></div></div></div></div>

            <div className="mt-6 rounded-2xl border border-[#dcebea] bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h3 className="text-sm font-bold">Danh sách phòng</h3><p className="mt-1 text-[11px] text-slate-400">Tìm kiếm và lọc trạng thái theo thời gian thực</p></div><div className="flex flex-wrap items-center gap-2"><div className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2"><Search size={14} className="text-slate-400" /><input value={tuKhoa} onChange={(e) => setTuKhoa(e.target.value)} className="w-36 bg-transparent text-xs outline-none placeholder:text-slate-400" placeholder="Tìm phòng, khách..." /></div><select value={boLoc} onChange={(e) => setBoLoc(e.target.value as TrangThaiPhong | 'Tất cả')} className="rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-500 outline-none"><option>Tất cả</option><option>Đang ở</option><option>Trống</option><option>Dọn phòng</option><option>Bảo trì</option></select></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="border-y border-slate-100 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="py-3">Phòng</th><th className="py-3">Loại phòng</th><th className="py-3">Khách hiện tại</th><th className="py-3">Giá / đêm</th><th className="py-3">Trạng thái</th><th /></tr></thead><tbody className="divide-y divide-slate-100">{phongHienThi.map((phong) => <tr key={phong.ma} className="transition hover:bg-[#f7fbfa]"><td className="py-3 font-bold">{phong.ma}</td><td className="py-3 text-slate-600">{phong.ten}</td><td className="py-3 text-slate-600">{phong.khach}</td><td className="py-3 text-slate-600">{phong.gia}</td><td className="py-3"><span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-semibold ${phong.mau === 'xanh' ? 'bg-[#e8f0fb] text-[#4171ae]' : phong.mau === 'la' ? 'bg-[#e8f5ee] text-[#32916b]' : phong.mau === 'cam' ? 'bg-[#fff0e5] text-[#c77b46]' : 'bg-slate-100 text-slate-500'}`}>{phong.trangThai}</span></td><td className="py-3 text-right"><button onClick={() => hienThongBao(`Đã mở chi tiết phòng ${phong.ma}`)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-[#12626b]">...</button></td></tr>)}</tbody></table></div></div>
            <div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[#eaf7f4] p-5"><div className="flex size-9 items-center justify-center rounded-xl bg-white text-[#16806e]"><CalendarCheck size={18} /></div><h3 className="mt-4 text-sm font-bold text-[#12626b]">12 lượt nhận phòng</h3><p className="mt-1 text-xs leading-5 text-[#56807e]">Hãy chuẩn bị sẵn chìa khóa và thông tin khách trước 14:00 hôm nay.</p></div><div className="rounded-2xl bg-[#fff4e8] p-5"><div className="flex size-9 items-center justify-center rounded-xl bg-white text-[#d7854f]"><Coffee size={18} /></div><h3 className="mt-4 text-sm font-bold text-[#a66034]">7 yêu cầu dịch vụ</h3><p className="mt-1 text-xs leading-5 text-[#9d765c]">Có 4 yêu cầu bữa sáng và 3 yêu cầu giặt ủi đang chờ xử lý.</p></div><div className="rounded-2xl bg-[#f0edfa] p-5"><div className="flex size-9 items-center justify-center rounded-xl bg-white text-[#8466b7]"><Sparkles size={18} /></div><h3 className="mt-4 text-sm font-bold text-[#695092]">Gợi ý doanh thu</h3><p className="mt-1 text-xs leading-5 text-[#776e91]">Công suất cuối tuần tăng 18%. Có thể điều chỉnh giá Deluxe.</p></div></div>
          </>}
        </div>
      </section>

      {thongBao && <div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-xl bg-[#132b35] px-4 py-3 text-xs font-medium text-white shadow-xl">{thongBao}</div>}
      {moDatPhong && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#102f3a]/50 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h3 className="font-bold">Tạo đặt phòng mới</h3><p className="mt-1 text-xs text-slate-400">Thông tin sẽ được đưa vào lịch đặt phòng</p></div><button onClick={() => setMoDatPhong(false)} aria-label="Đóng"><X size={18} /></button></div><div className="mt-5 space-y-3"><input className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-[#12626b]" placeholder="Tên khách hàng" /><div className="grid grid-cols-2 gap-3"><input className="rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none" placeholder="Ngày nhận phòng" /><input className="rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none" placeholder="Ngày trả phòng" /></div><select className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none"><option>Chọn loại phòng</option><option>Standard King</option><option>Deluxe Garden</option><option>Family Suite</option></select></div><div className="mt-6 flex justify-end gap-2"><button onClick={() => setMoDatPhong(false)} className="rounded-xl px-4 py-2 text-xs font-semibold text-slate-500">Hủy</button><button onClick={() => { setMoDatPhong(false); hienThongBao('Đã tạo đặt phòng thành công') }} className="rounded-xl bg-[#123f50] px-4 py-2 text-xs font-semibold text-white">Lưu đặt phòng</button></div></div></div>}
    </main>
  )
}
