'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, Bell, CalendarDays, ChevronRight, CircleDollarSign, Home, LogIn, Mail, MapPin, Menu, Phone, Sparkles, Star, Users, X } from 'lucide-react'

type View = 'Tổng quan' | 'Doanh thu' | 'Đặt phòng' | 'Lịch của tôi' | 'Đánh giá' | 'Thông báo'
const today = new Date().toISOString().split('T')[0]
const rooms = [
  ['Phòng đơn', 'P.101', 680000, 28, '72%', 'Nguyễn Minh Anh'],
  ['Phòng đôi', 'P.102', 920000, 46, '86%', 'Trống'],
  ['Phòng VIP', 'P.201', 1650000, 39, '91%', 'Trần Hoàng Nam'],
  ['Phòng gia đình', 'P.202', 2100000, 22, '64%', 'Lê Thu Hà'],
  ['Homestay nguyên căn', 'H.01', 2850000, 18, '58%', 'Phạm Gia Bảo'],
  ['Villa homestay', 'H.02', 3900000, 13, '49%', 'Trống'],
]
const bookings = [['BK-0925', 'Mai Linh', 'Phòng VIP · P.201', '25/09 – 28/09/2026', '1.650.000đ', 'Đã cọc 500.000đ'], ['BK-0926', 'Quốc Huy', 'Phòng đôi · P.102', '25/09 – 27/09/2026', '1.840.000đ', 'Đã cọc 920.000đ'], ['BK-0927', 'An Nhiên', 'Villa homestay · H.02', '26/09 – 29/09/2026', '11.700.000đ', 'Chờ cọc']]

export default function HomePage() {
  const [view, setView] = useState<View>('Tổng quan')
  const [menu, setMenu] = useState(false)
  const [auth, setAuth] = useState<'login' | 'register' | null>(null)
  const [brand, setBrand] = useState(false)
  const [booking, setBooking] = useState(false)
  const [payment, setPayment] = useState(false)
  const [depositSent, setDepositSent] = useState(false)
  const [adminApproved, setAdminApproved] = useState(false)
  const [selectedRoom, setSelectedRoom] = useState<string | null>(null)
  const [notice, setNotice] = useState(false)
  const [noticeText, setNoticeText] = useState('')
  const [role, setRole] = useState('Khách hàng')
  const [nguoiDung, setNguoiDung] = useState<{email:string; role:string} | null>(null)
  const flash = (text: string) => { setNoticeText(text); window.setTimeout(() => setNoticeText(''), 2600) }
  const xuLyDangNhap = (email: string, matKhau: string) => {
    if (email === 'admin@auroranest.vn' && matKhau === 'Aurora@2026') {
      setNguoiDung({ email, role: 'Quản trị viên' }); setAuth(null); flash('Đăng nhập quản trị viên thành công')
    } else if (email && matKhau) {
      setNguoiDung({ email, role: 'Khách hàng' }); setAuth(null); flash('Đăng nhập khách hàng thành công')
    } else flash('Vui lòng nhập đầy đủ email và mật khẩu')
  }
  const nav: [string, View][] = [['Tổng quan', 'Tổng quan'], ['Doanh thu', 'Doanh thu'], ['Đặt phòng', 'Đặt phòng'], ['Lịch của tôi', 'Lịch của tôi'], ['Đánh giá', 'Đánh giá'], ['Thông báo', 'Thông báo']]
  return <main className="min-h-screen bg-[#f8f7f3] text-[#203235]">
    <header className="sticky top-0 z-30 border-b border-[#e7e3da] bg-[#fffefa]/95 px-5 py-4 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between"><button onClick={() => setBrand(true)} className="flex items-center gap-3 text-left"><span className="flex size-10 items-center justify-center rounded-2xl bg-[#173b3d] text-[#e5b875]"><Sparkles size={19}/></span><span><b className="block text-base tracking-tight">Aurora Nest</b><small className="text-[10px] uppercase tracking-[.2em] text-[#87938f]">Hotel · Homestay</small></span></button><nav className="hidden items-center gap-1 lg:flex">{nav.map(([label, target]) => <button key={label} onClick={() => setView(target)} className={`rounded-xl px-3 py-2 text-xs font-medium ${view === target ? 'bg-[#173b3d] text-white' : 'text-[#687873] hover:bg-[#eef0ea]'}`}>{label}</button>)}</nav><div className="flex items-center gap-2"><button onClick={() => setNotice(true)} aria-label="Thông báo" className="relative rounded-xl p-2 text-[#59706b] hover:bg-[#eef0ea]"><Bell size={18}/><i className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-[#d7765d]"/></button>{nguoiDung ? <button onClick={() => { setNguoiDung(null); flash('Đã đăng xuất khỏi Aurora Nest') }} className="rounded-xl border border-[#d9ddd5] px-3 py-2 text-xs font-semibold"><span className="hidden sm:inline">{nguoiDung.role} · </span>Đăng xuất</button> : <><button onClick={() => setAuth('login')} className="hidden rounded-xl border border-[#d9ddd5] px-3 py-2 text-xs font-semibold sm:block">Đăng nhập</button><button onClick={() => setAuth('register')} className="rounded-xl bg-[#e5b875] px-3 py-2 text-xs font-bold text-[#173b3d]">Đăng ký</button></>}<button onClick={() => setMenu(!menu)} className="rounded-xl p-2 lg:hidden"><Menu size={19}/></button></div></div>{menu && <div className="mx-auto mt-3 grid max-w-7xl gap-1 rounded-2xl bg-[#173b3d] p-2 lg:hidden">{nav.map(([label, target]) => <button key={label} onClick={() => {setView(target);setMenu(false)}} className="rounded-xl px-3 py-3 text-left text-sm text-white hover:bg-white/10">{label}</button>)}</div>}</header>
    <section className="mx-auto max-w-7xl px-5 py-7 sm:px-8"><div className="relative overflow-hidden rounded-[28px] bg-[#173b3d] p-7 text-white shadow-xl sm:p-10"><img src="/images/aurora-hero.png" alt="Sân vườn Aurora Nest" className="absolute inset-0 size-full object-cover opacity-25"/><div className="relative max-w-2xl"><p className="text-xs uppercase tracking-[.2em] text-[#e5b875]">Không gian nghỉ dưỡng tinh tế</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">Chào mừng đến Aurora Nest</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#d4e1dc]">Nền tảng quản lý khách sạn và homestay — nơi mọi đặt phòng, dịch vụ và doanh thu được vận hành rõ ràng.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => setBooking(true)} className="rounded-xl bg-[#e5b875] px-4 py-3 text-xs font-bold text-[#173b3d]">Đặt phòng ngay</button><button onClick={() => setBrand(true)} className="rounded-xl border border-white/30 px-4 py-3 text-xs font-semibold text-white">Về Aurora Nest</button></div></div></div>
      {view !== 'Tổng quan' && <button onClick={() => setView('Tổng quan')} className="mb-4 inline-flex items-center gap-2 rounded-xl border border-[#d9ddd5] bg-[#fffefa] px-4 py-2.5 text-xs font-semibold text-[#28665d] shadow-sm transition hover:-translate-x-0.5 hover:bg-[#eef4ef]"><ArrowLeft size={17}/><span className="sr-only">Trở về tổng quan</span></button>}<div className="mt-6">{view === 'Tổng quan' && <Dashboard go={setView} openRoom={setSelectedRoom} />}{view === 'Doanh thu' && <Revenue />}{view === 'Đặt phòng' && <Bookings />}{view === 'Lịch của tôi' && <MyBookings depositSent={depositSent} adminApproved={adminApproved} openBooking={() => setBooking(true)} />}{view === 'Đánh giá' && <Reviews />}{view === 'Thông báo' && <Notifications depositSent={depositSent} approve={() => {setAdminApproved(true);flash('Admin đã duyệt và xác nhận đặt phòng')}} />}</div></section>
    {selectedRoom && <RoomDetailModal code={selectedRoom} close={() => setSelectedRoom(null)}/>} {booking && <BookingModal close={() => setBooking(false)} submit={() => {setBooking(false);setPayment(true);flash('Đặt phòng đã tạo — vui lòng chuyển khoản tiền cọc')}}/>}{payment && <PaymentModal close={() => setPayment(false)} sent={() => {setDepositSent(true);setPayment(false);flash('Đã gửi xác nhận chuyển khoản, chờ admin duyệt')}}/>}{auth && <AuthModal mode={auth} setMode={setAuth} close={() => setAuth(null)} role={role} setRole={setRole} submit={xuLyDangNhap}/>} {brand && <BrandModal close={() => setBrand(false)}/>} {notice && <NotificationsModal close={() => setNotice(false)} open={setView}/>} {noticeText && <div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-xl bg-[#173b3d] px-4 py-3 text-xs font-semibold text-white shadow-xl">{noticeText}</div>}
  </main>
}
function Dashboard({go,openRoom}:{go:(v:View)=>void;openRoom:(code:string)=>void}) { return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Doanh thu tháng này','186.450.000đ','+12,8%',CircleDollarSign,'Doanh thu'],['Đặt phòng hôm nay','12 lượt','3 lượt nhận phòng',CalendarDays,'Đặt phòng'],['Khách đang ở','34 khách','78,4% công suất',Users,'Đặt phòng'],['Điểm đánh giá','4,8 / 5','126 đánh giá',Star,'Đánh giá']].map(([a,b,c,I,v])=><button key={a as string} onClick={()=>go(v as View)} className="rounded-2xl border border-[#e5e3db] bg-[#fffefa] p-5 text-left shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><span className="flex size-10 items-center justify-center rounded-xl bg-[#e8f0eb] text-[#28665d]"><I size={18}/></span><p className="mt-5 text-xs text-[#7b8985]">{a as string}</p><b className="mt-1 block text-xl">{b as string}</b><small className="mt-2 block text-[10px] text-[#4d9a78]">{c as string}</small></button>)}</div><div className="mt-6 rounded-2xl border border-[#e5e3db] bg-[#fffefa] p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Doanh thu theo loại phòng</h2><p className="mt-1 text-xs text-[#7b8985]">Phòng VIP và phòng đôi đang được ưu tiên nhiều nhất.</p></div><button onClick={()=>go('Doanh thu')} className="text-xs font-semibold text-[#28665d]">Xem đầy đủ <ChevronRight className="inline" size={14}/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rooms.map(([name,code,price,amount,rate])=><button key={code as string} onClick={() => openRoom(code as string)} className="w-full rounded-xl bg-[#f3f2ec] p-4 text-left transition hover:-translate-y-0.5 hover:bg-[#eaf1ed]"><div className="flex justify-between"><b className="text-sm">{name as string}</b><span className="text-xs text-[#28665d]">{rate as string}</span></div><p className="mt-2 text-xs text-[#71807c]">{code as string} · {amount as number} lượt đặt</p><strong className="mt-2 block text-sm">{(amount as number * price as number).toLocaleString('vi-VN')}đ</strong></button>)}</div></div></>}
function Revenue(){return <section className="rounded-2xl border border-[#e5e3db] bg-[#fffefa] p-5"><h2 className="text-xl font-semibold">Báo cáo doanh thu chi tiết</h2><p className="mt-1 text-xs text-[#71807c]">Tháng 9/2026 · Tổng doanh thu phòng và dịch vụ: 186.450.000đ</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="border-y border-[#eeeae1] text-[10px] uppercase tracking-wider text-[#8b9894]"><tr><th className="py-3">Loại lưu trú</th><th>Lượt đặt</th><th>Tỷ lệ ưu tiên</th><th>Doanh thu phòng</th><th>Xu hướng</th></tr></thead><tbody className="divide-y divide-[#eeeae1]">{rooms.map(([name,code,price,amount,rate])=><tr key={code as string}><td className="py-4 font-semibold">{name as string}<small className="ml-2 text-[#8b9894]">{code as string}</small></td><td>{amount as number}</td><td><span className="rounded-full bg-[#e5f0eb] px-2 py-1 text-[#28665d]">{rate as string}</span></td><td className="font-semibold">{(amount as number * price as number).toLocaleString('vi-VN')}đ</td><td className="text-[#4d9a78]">Tăng 12,8%</td></tr>)}</tbody></table></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Phòng đôi','86% · được đặt nhiều nhất'],['Phòng VIP','91% · giá trị cao nhất'],['Villa homestay','49% · cần ưu đãi cuối tuần']].map(([a,b])=><div className="rounded-xl bg-[#173b3d] p-4 text-white" key={a}><b className="text-sm">{a}</b><p className="mt-2 text-xs text-[#c9d8d3]">{b}</p></div>)}</div></section>}
function Bookings(){return <section className="rounded-2xl border border-[#e5e3db] bg-[#fffefa] p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Chi tiết đặt phòng</h2><p className="mt-1 text-xs text-[#71807c]">Theo dõi lịch nhận phòng, trả phòng và tiền cọc.</p></div><button className="rounded-xl bg-[#173b3d] px-3 py-2 text-xs font-semibold text-white">Xuất danh sách</button></div><div className="mt-5 space-y-3">{bookings.map(b=><article className="rounded-2xl bg-[#f3f2ec] p-4" key={b[0]}><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-[10px] text-[#8b9894]">{b[0]}</span><h3 className="mt-1 font-semibold">{b[1]}</h3><p className="mt-1 text-xs text-[#71807c]">{b[2]} · {b[3]}</p></div><div className="text-right"><b>{b[4]}</b><p className="mt-1 text-[11px] text-[#28665d]">{b[5]}</p></div></div></article>)}</div></section>}
function MyBookings({depositSent,adminApproved,openBooking}:{depositSent:boolean;adminApproved:boolean;openBooking:()=>void}){return <section className="rounded-2xl border border-[#e5e3db] bg-[#fffefa] p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Lịch đã và đang đặt phòng</h2><p className="mt-1 text-xs text-[#71807c]">Theo dõi thông tin khách, số ngày ở, tiền cọc và trạng thái duyệt.</p></div><button onClick={openBooking} className="rounded-xl bg-[#173b3d] px-3 py-2 text-xs font-semibold text-white">Đặt phòng mới</button></div><div className="mt-5 space-y-3">{[['BK-0926','Phòng đôi · P.102','25/09 – 27/09/2026','2 đêm','1.840.000đ','Đang ở'],['BK-0914','Phòng đơn · P.101','20/09 – 22/09/2026','2 đêm','1.360.000đ','Đã hoàn tất']].map(b=><article key={b[0]} className="rounded-2xl bg-[#f3f2ec] p-4"><div className="flex flex-wrap justify-between gap-3"><div><span className="text-[10px] text-[#8b9894]">{b[0]}</span><h3 className="mt-1 font-semibold">{b[1]}</h3><p className="mt-1 text-xs text-[#71807c]">{b[2]} · <b>{b[3]}</b></p></div><div className="text-right"><b>{b[4]}</b><p className="mt-1 text-xs text-[#28665d]">{b[5]}</p></div></div><p className="mt-3 border-t border-[#e5e3db] pt-3 text-xs text-[#71807c]">Khách: Nguyễn Minh Anh · Nhận phòng 14:00 · Trả phòng 12:00</p></article>)}</div><div className="mt-5 rounded-2xl border border-[#e5b875] bg-[#fff7e8] p-4 text-xs"><b>Đơn đặt phòng mới · P.102</b><p className="mt-2 text-[#71807c]">2 đêm · Tổng 1.840.000đ · Tiền cọc 920.000đ · Mã chuyển khoản: AURORA-BK0926</p><p className="mt-2 font-semibold text-[#28665d]">{adminApproved?'Đã được admin duyệt và xác nhận đặt phòng':depositSent?'Đã gửi xác nhận chuyển khoản · Chờ admin duyệt':'Chưa xác nhận chuyển khoản'}</p></div></section>}
function PaymentModal({close,sent}:{close:()=>void;sent:()=>void}){return <Modal title="Thanh toán tiền cọc" close={close}><p className="text-xs leading-5 text-[#71807c]">Vui lòng chuyển khoản tiền cọc, sau đó bấm xác nhận để admin kiểm tra và duyệt đặt phòng.</p><div className="mt-4 rounded-2xl bg-[#eaf1ed] p-4 text-sm"><b>Ngân hàng Aurora Nest</b><p className="mt-2 text-xs">STK: <b>1900 6868 2026</b></p><p className="mt-1 text-xs">Chủ tài khoản: AURORA NEST HOTEL</p><p className="mt-1 text-xs">Nội dung: <b>AURORA-BK0926</b></p><p className="mt-3 text-xs font-semibold text-[#28665d]">Tiền cọc cần chuyển: 920.000đ</p></div><button onClick={sent} className="mt-5 w-full rounded-xl bg-[#173b3d] py-3 text-xs font-bold text-white">Tôi đã chuyển khoản</button></Modal>}
function Reviews(){return <section className="rounded-2xl border border-[#e5e3db] bg-[#fffefa] p-5"><h2 className="text-xl font-semibold">Đánh giá của khách đã lưu trú</h2><p className="mt-1 text-xs text-[#71807c]">Mỗi đánh giá được liên kết với đúng phòng khách đã từng ở.</p><div className="mt-5 space-y-3">{[['Mai Linh','Phòng VIP · P.201','5,0','Không gian yên tĩnh, hồ bơi rất đẹp.'],['Nguyễn Minh Anh','Phòng đơn · P.101','4,8','Phòng sạch, ban công thoáng và nhân viên thân thiện.'],['Phạm Gia Bảo','Homestay nguyên căn · H.01','4,9','Rất phù hợp cho gia đình, bếp và sân vườn đầy đủ.']].map(r=><article key={r[0]} className="rounded-2xl border border-[#eeeae1] p-4"><div className="flex justify-between"><div><b>{r[0]}</b><p className="mt-1 text-xs text-[#28665d]">{r[1]}</p></div><span className="flex items-center gap-1 text-sm font-bold text-[#b7792d]"><Star size={14} fill="currentColor"/>{r[2]}</span></div><p className="mt-3 text-sm leading-6 text-[#5d706b]">“{r[3]}”</p></article>)}</div></section>}
function Notifications({depositSent,approve}:{depositSent:boolean;approve:()=>void}){return <section className="rounded-2xl border border-[#e5e3db] bg-[#fffefa] p-5"><h2 className="text-xl font-semibold">Thông báo vận hành</h2><div className="mt-5 space-y-3">{[['Đặt phòng mới','Mai Linh vừa đặt Phòng VIP P.201, nhận phòng hôm nay lúc 14:00.','2 phút trước'],['Cần xác nhận cọc','Quốc Huy đã đặt Phòng đôi P.102, tiền cọc 920.000đ đang chờ xác nhận.','18 phút trước'],['Khách sắp trả phòng','Nguyễn Minh Anh trả Phòng đơn P.101 lúc 08:30 ngày mai.','1 giờ trước'],['Dịch vụ mới','Phòng P.201 yêu cầu set BBQ cho 4 người lúc 19:00.','2 giờ trước']].map(n=><article key={n[0]} className="flex gap-3 rounded-2xl bg-[#f3f2ec] p-4"><span className="mt-1 flex size-8 shrink-0 items-center justify-center rounded-xl bg-[#e5b875] text-[#173b3d]"><Bell size={15}/></span><div><b className="text-sm">{n[0]}</b><p className="mt-1 text-xs leading-5 text-[#657772]">{n[1]}</p><small className="mt-2 block text-[10px] text-[#8b9894]">{n[2]}</small>{depositSent && n[0]==='Cần xác nhận cọc' && <button onClick={approve} className="mt-3 rounded-lg bg-[#173b3d] px-3 py-2 text-[11px] font-bold text-white">Duyệt tiền cọc và xác nhận đặt phòng</button>}</div></article>)}</div></section>}
function RoomDetailModal({code,close}:{code:string;close:()=>void}){const room=rooms.find(r=>r[1]===code); const guests:Record<string,string[][]>={'P.101':[['Nguyễn Minh Anh','20/09 – 22/09/2026','1.360.000đ','Đã hoàn tất'],['Lê Hoàng','25/09 – 27/09/2026','1.360.000đ','Đã cọc 680.000đ']], 'P.102':[['Quốc Huy','25/09 – 27/09/2026','1.840.000đ','Đã cọc 920.000đ']], 'P.201':[['Mai Linh','25/09 – 28/09/2026','4.950.000đ','Đã cọc 1.650.000đ']], 'P.202':[['Lê Thu Hà','12/09 – 15/09/2026','6.300.000đ','Đã hoàn tất']], 'H.01':[['Phạm Gia Bảo','05/09 – 08/09/2026','8.550.000đ','Đã hoàn tất']], 'H.02':[['An Nhiên','26/09 – 29/09/2026','11.700.000đ','Chờ cọc']]}; const rows=guests[code]||[]; return <Modal title={`Chi tiết ${room?.[0] || 'phòng'} · ${code}`} close={close}><p className="text-xs text-[#71807c]">Danh sách khách đã đặt, lịch lưu trú và trạng thái thanh toán.</p><div className="mt-4 rounded-2xl bg-[#eaf1ed] p-4"><div className="flex justify-between text-sm"><b>{room?.[0]}</b><span>{room?.[4]} ưu tiên</span></div><p className="mt-2 text-xs text-[#5d706b]">{room?.[3]} lượt đặt trong tháng · Doanh thu {(Number(room?.[2]) * Number(room?.[3])).toLocaleString('vi-VN')}đ</p></div><div className="mt-4 space-y-3">{rows.map(g=><div key={`${g[0]}-${g[1]}`} className="rounded-2xl border border-[#eeeae1] p-4"><div className="flex justify-between gap-3"><div><b className="text-sm">{g[0]}</b><p className="mt-1 text-xs text-[#71807c]">{g[1]}</p></div><span className="text-right text-xs font-semibold text-[#28665d]">{g[2]}<small className="mt-1 block font-normal text-[#8b9894]">{g[3]}</small></span></div></div>)}</div><button onClick={close} className="mt-5 w-full rounded-xl bg-[#173b3d] py-3 text-xs font-bold text-white">Đóng chi tiết</button></Modal>}
function BookingModal({close,submit}:{close:()=>void;submit:()=>void}){return <Modal title="Tạo đặt phòng" close={close}><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Ngày nhận phòng<input type="date" min={today} defaultValue={today} className="mt-2 w-full rounded-xl border p-3 text-sm"/></label><label className="text-xs">Ngày trả phòng<input type="date" min={today} className="mt-2 w-full rounded-xl border p-3 text-sm"/></label></div><label className="mt-3 block text-xs">Khách hàng<input placeholder="Họ và tên khách" className="mt-2 w-full rounded-xl border p-3 text-sm"/></label><label className="mt-3 block text-xs">Loại phòng<select className="mt-2 w-full rounded-xl border p-3 text-sm">{rooms.map(r=><option key={r[0]}>{r[0]} · {Number(r[2]).toLocaleString('vi-VN')}đ/đêm</option>)}</select></label><div className="mt-4 rounded-2xl bg-[#eaf1ed] p-4 text-xs"><div className="flex justify-between"><span>Tiền phòng dự kiến</span><b>1.840.000đ</b></div><div className="mt-2 flex justify-between"><span>Tiền cọc đề xuất (50%)</span><b className="text-[#28665d]">920.000đ</b></div><p className="mt-2 text-[10px] text-[#71807c]">Ngày đã qua bị khóa; số tiền còn lại thanh toán khi check-out.</p></div><button onClick={submit} className="mt-5 w-full rounded-xl bg-[#173b3d] py-3 text-xs font-bold text-white">Xác nhận đặt phòng và tiền cọc</button></Modal>}
function AuthModal({mode,setMode,close,role,setRole,submit}:{mode:'login'|'register';setMode:(m:'login'|'register')=>void;close:()=>void;role:string;setRole:(r:string)=>void;submit:(email:string,matKhau:string)=>void}){const [email,setEmail]=useState(''); const [matKhau,setMatKhau]=useState(''); const dangKy=mode==='register'; return <Modal title={dangKy?'Tạo tài khoản khách hàng':'Đăng nhập Aurora Nest'} close={close}><p className="text-xs text-[#71807c]">{dangKy?'Tài khoản đăng ký mới mặc định là Khách hàng. Nhân viên lễ tân chỉ được cấp quyền bởi quản trị viên.':'Đăng nhập bằng tài khoản được cấp. Tài khoản quản trị viên mặc định có sẵn trong bản demo.'}</p>{!dangKy && <div className="mt-4 rounded-2xl bg-[#eaf1ed] p-3 text-xs text-[#28665d]"><b>Tài khoản quản trị viên mặc định</b><p className="mt-1">admin@auroranest.vn · Aurora@2026</p></div>}{dangKy && <><label className="mt-4 block text-xs">Họ và tên<input required placeholder="Nguyễn Văn A" className="mt-2 w-full rounded-xl border p-3 text-sm"/></label><label className="mt-3 block text-xs">S�� điện thoại<input required type="tel" placeholder="0901 234 567" className="mt-2 w-full rounded-xl border p-3 text-sm"/></label><label className="mt-3 block text-xs">Số CCCD<input required inputMode="numeric" placeholder="012345678901" className="mt-2 w-full rounded-xl border p-3 text-sm"/></label></>}<label className="mt-4 block text-xs">Email<input required value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com" className="mt-2 w-full rounded-xl border p-3 text-sm"/></label><label className="mt-3 block text-xs">Mật khẩu<input required value={matKhau} onChange={e=>setMatKhau(e.target.value)} type="password" placeholder="Mật khẩu tối thiểu 8 ký tự" className="mt-2 w-full rounded-xl border p-3 text-sm"/></label>{dangKy ? <div className="mt-3 rounded-xl bg-[#f3f2ec] p-3 text-xs"><b>Vai trò mặc định: Khách hàng</b><p className="mt-1 text-[#71807c]">Khách hàng là lựa chọn duy nhất khi đăng ký. Nhân viên lễ tân chỉ được quản trị viên cấp quyền.</p></div> : <div className="mt-3 rounded-xl bg-[#eaf1ed] p-3 text-xs"><b>Vai trò được xác định tự động</b><p className="mt-1 text-[#71807c]">Tài khoản admin mặc định sẽ vào vai trò Quản trị viên. Các tài khoản khác đăng nhập với vai trò Khách hàng.</p></div>}<button onClick={()=>submit(email,matKhau)} className="mt-5 w-full rounded-xl bg-[#173b3d] py-3 text-xs font-bold text-white">{dangKy?'Đăng ký tài khoản khách hàng':'Đăng nhập'}</button><button onClick={()=>setMode(dangKy?'login':'register')} className="mt-3 w-full text-xs text-[#28665d]">{dangKy?'Đã có tài khoản? Đăng nhập':'Chưa có tài khoản? Đăng ký khách hàng'}</button></Modal>}
function BrandModal({close}:{close:()=>void}){return <Modal title="Aurora Nest" close={close}><div className="space-y-3 text-sm text-[#5d706b]"><p className="flex gap-3"><MapPin className="shrink-0 text-[#28665d]" size={18}/>28 Đường Mây Trắng, Đà Lạt, Lâm Đồng</p><p className="flex gap-3"><Phone className="shrink-0 text-[#28665d]" size={18}/>Hotline: 0909 268 888 · 24/7</p><p className="flex gap-3"><Mail className="shrink-0 text-[#28665d]" size={18}/>hello@auroranest.vn</p><p className="rounded-xl bg-[#eaf1ed] p-3 text-xs">Chi nhánh Đà Lạt · Chi nhánh Hội An · Chi nh��nh Phú Quốc</p><p className="text-xs">Fanpage Facebook: Aurora Nest Vietnam<br/>Zalo OA: Aurora Nest Official</p></div></Modal>}
function NotificationsModal({close,open}:{close:()=>void;open:(v:View)=>void}){return <Modal title="Thông báo mới" close={close}><p className="text-sm font-semibold">Mai Linh vừa đặt Phòng VIP P.201</p><p className="mt-2 text-xs leading-5 text-[#71807c]">Nhận phòng hôm nay lúc 14:00 · 3 đêm · Tổng 4.950.000đ · Đã cọc 1.650.000đ.</p><button onClick={()=>{close();open('Thông báo')}} className="mt-5 w-full rounded-xl bg-[#173b3d] py-3 text-xs font-bold text-white">Xem tất cả thông báo</button></Modal>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#173b3d]/50 p-4 backdrop-blur-sm" onClick={close}><div className="w-full max-w-lg rounded-3xl bg-[#fffefa] p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={close} aria-label="Đóng" className="rounded-xl p-2 hover:bg-[#f0eee7]"><X size={18}/></button></div>{children}</div></div>}
