# Generated by Django 6.1.1 on 2026-09-25 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('view', models.CharField(max_length=180)),
                ('bathroom', models.CharField(max_length=180)),
                ('image', models.CharField(max_length=200)),
                ('amenities', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bookings.roomtype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=24, unique=True)),
                ('guest_name', models.CharField(max_length=120)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Chờ cọc'), ('deposit_sent', 'Đã gửi xác nhận cọc'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã hoàn tất')], default='pending', max_length=20)),
                ('deposit_amount', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('deposit_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.roomtype')),
            ],
        ),
    ]
